### ISSUE TITLE
Implement landing page

### ISSUE THREAD

**Issue by jgualtieri** [dartmouth-cs52-17S/project-client-roommatefinder#5]
Route: "/"

The page that the user will see upon entering into the site - this page will have two inputs and three buttons:

**Center of page**

Location input - allows users to enter the location of their off term
Date input - allows users to enter the date of their off term

Go button - takes the user's location and date and redirects to the "/sample-matches" page - intended to give the user a taste of what the service has to offer

**Top right corner**

Sign up button - redirects to the "sign-up page"
Login button - redirects to the "log-in page"

See mockups - [](https://www.figma.com/file/BDBHIIUpPzMfwc8veVhSHiDO/Dartmouth-Roommate-Finder-Mockups)

**Comment by ianmarx** [comment]
Added basic landing page container. Still needs styling and wiring with Redux.
